var cson = require('cson')

var configFile = 'config.cson'
var config = {}

try {
	console.log("Reading config '%s'", configFile)
	config = cson.load(configFile)
	console.log(JSON.stringify(config, null, 4))
	console.log('\n')
} catch (err) {
	
	if (err.code === 'ENOENT') {
		console.log("'" + configFile + "' (config) not found, edit and rename 'default.cson' to '" + configFile + "'");
	} else {
		console.log(err);
	}
	
	process.exit();
}

module.exports = config;

// ---
// generated by coffee-script 1.9.2